server {

    listen 80;

    server_name localhost;

    root /var/www/public;

    index index.php index.html;

    charset utf-8;


    # حجم الملفات المسموح برفعها
    client_max_body_size 100M;


    # Laravel Routes
    location / {

        try_files $uri $uri/ /index.php?$query_string;

    }


    # PHP Processing
    location ~ \.php$ {

        include fastcgi_params;

        fastcgi_pass app:9000;

        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_param PATH_INFO $fastcgi_path_info;

    }


    # منع الوصول للملفات المخفية
    # مثل .env و .git

    location ~ /\.(?!well-known).* {

        deny all;

    }


    # تجاهل طلبات favicon

    location = /favicon.ico {

        access_log off;

        log_not_found off;

    }


    # تجاهل robots

    location = /robots.txt {

        access_log off;

        log_not_found off;

    }


    # Logs

    access_log /var/log/nginx/access.log;

    error_log /var/log/nginx/error.log;

}
